version: 2

jobs:
  us-east-1-build:
    docker:
      - image: paulmarsicloud/terragrunt-awscli
    environment:
      TF_VAR_public_ip: <REPLACE ME>
      AWS_DEFAULT_REGION: us-east-1
    working_directory: ~/openvpn-ephemeral
    steps:
      - checkout
      - run:
          name: build
          command: |
            terragrunt init --terragrunt-non-interactive
            terragrunt apply -auto-approve
      - store_artifacts:
          path: ~/openvpn-ephemeral/openvpn.ovpn

  us-east-1-destroy:
    docker:
      - image: paulmarsicloud/terragrunt-awscli
    environment:
      TF_VAR_public_ip: <REPLACE ME>
      AWS_DEFAULT_REGION: us-east-1
    working_directory: ~/openvpn-ephemeral
    steps:
      - checkout
      - run:
          name: destroy
          command: |
            terragrunt init --terragrunt-non-interactive
            terragrunt destroy -auto-approve
  us-west-2-build:
    docker:
      - image: paulmarsicloud/terragrunt-awscli
    environment:
      TF_VAR_public_ip: <REPLACE ME>
      AWS_DEFAULT_REGION: us-west-2
    working_directory: ~/openvpn-ephemeral
    steps:
      - checkout
      - run:
          name: build
          command: |
            terragrunt init --terragrunt-non-interactive
            terragrunt apply -auto-approve
      - store_artifacts:
          path: ~/openvpn-ephemeral/openvpn.ovpn

  us-west-2-destroy:
    docker:
      - image: paulmarsicloud/terragrunt-awscli
    environment:
      TF_VAR_public_ip: <REPLACE ME>
      AWS_DEFAULT_REGION: us-west-2
    working_directory: ~/openvpn-ephemeral
    steps:
      - checkout
      - run:
          name: destroy
          command: |
            terragrunt init --terragrunt-non-interactive
            terragrunt destroy -auto-approve
  ap-southeast-2-build:
    docker:
      - image: paulmarsicloud/terragrunt-awscli
    environment:
      TF_VAR_public_ip: <REPLACE ME>
      AWS_DEFAULT_REGION: ap-southeast-2
    working_directory: ~/openvpn-ephemeral
    steps:
      - checkout
      - run:
          name: build
          command: |
            terragrunt init --terragrunt-non-interactive
            terragrunt apply -auto-approve
      - store_artifacts:
          path: ~/openvpn-ephemeral/openvpn.ovpn

  ap-southeast-2-destroy:
    docker:
      - image: paulmarsicloud/terragrunt-awscli
    environment:
      TF_VAR_public_ip: <REPLACE ME>
      AWS_DEFAULT_REGION: ap-southeast-2
    working_directory: ~/openvpn-ephemeral
    steps:
      - checkout
      - run:
          name: destroy
          command: |
            terragrunt init --terragrunt-non-interactive
            terragrunt destroy -auto-approve
workflows:
  version: 2
  us-east-1:
    jobs:
      - approve_build:
          type: approval
      - us-east-1-build:
          requires:
            - approve_build
      - approve_destroy:
          type: approval
          requires:
            - us-east-1-build
      - us-east-1-destroy:
          requires:
            - approve_destroy
  us-west-2:
    jobs:
      - approve_build:
          type: approval
      - us-west-2-build:
          requires:
            - approve_build
      - approve_destroy:
          type: approval
          requires:
            - us-west-2-build
      - us-west-2-destroy:
          requires:
            - approve_destroy
  ap-southeast-2:
    jobs:
      - approve_build:
          type: approval
      - ap-southeast-2-build:
          requires:
            - approve_build
      - approve_destroy:
          type: approval
          requires:
            - ap-southeast-2-build
      - ap-southeast-2-destroy:
          requires:
            - approve_destroy
